- name: install cli
  become: true
  pacman:
    name:
      - grim
      - yazi
      - tmux
      - keepass
      - unzip
      - zip
      - zathura
      - zathura-pdf-poppler
      - zathura-cb
      - rlwrap
      - luarocks
    state: present
